package utils;

import com.google.common.collect.Lists;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.time.Month;
import java.util.Arrays;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.stream.Collectors;

import enums.Barangay;
import enums.BuildingMaterial;
import enums.BuildingType;
import enums.CivilStatus;
import enums.CookingFuel;
import enums.DeliveryPlace;
import enums.Education;
import enums.Enrollment;
import enums.FPMethod;
import enums.Facility;
import enums.GarbageDisposal;
import enums.HealthInsurance;
import enums.IncomeSource;
import enums.Lighting;
import enums.Nationality;
import enums.Ownership;
import enums.ParentalStatus;
import enums.ReasonForLeaving;
import enums.ReasonForTransfer;
import enums.ReasonOfVisit;
import enums.Relation;
import enums.ResidentType;
import enums.SchoolLevel;
import enums.Sex;
import enums.Skill;
import enums.SourceOfFP;
import enums.ToiletFacility;
import enums.WaterSource;
import enums.WorkStatus;
import enums.YesOrNo;
import models.Household;
import models.Record;
import models.Resident;
import models.Survey;
import play.Logger;

import static org.apache.poi.ss.usermodel.Row.MissingCellPolicy.RETURN_BLANK_AS_NULL;

/**
 * @author Maica Ballangan
 * @since v1
 */
public class ExcelUtils {

    public static List<Record> importExcel(File file) throws IOException {
        List<Record> records = Lists.newArrayList();
        boolean hasError = false;

        try {
            // Make sure to sort using Relation field so that head will be processed first
            FileInputStream fis = new FileInputStream(file);
            XSSFWorkbook wb = new XSSFWorkbook(fis);
            XSSFSheet sheet = wb.getSheetAt(0);
            Iterator<Row> itr = sheet.iterator();
            itr.next(); // skip header

            while (itr.hasNext()) {
                Row row = itr.next();

                try {
                    Household.HouseholdBuilder hhb = Household.builder();
                    Survey.SurveyBuilder sb = Survey.builder();
                    Resident.ResidentBuilder rb = Resident.builder();

                    Relation relation = Relation.getByCode(getIntCellValue(row, 30));
                    hhb.barangay(Barangay.getByDescription(getStringCellValue(row, 6))); //7
                    hhb.address(getStringCellValue(row, 8));// 9 rmflrblockno 99#
                    hhb.houseNo(getIntCellValue(row, 11)); //10 houseno 99#
                    hhb.street(getStringCellValue(row, 12)); //13
                    hhb.head(getStringCellValue(row, 14)); //15

                    if (Relation.Head.equals(relation)) {
                        // Household info
                        //getIntCellValue(cellIterator.next()); //1 id No (ignored)
                        //cellIterator.next(); //2 popcomNo TODO
                        //cellIterator.next(); //3 province
                        //cellIterator.next(); //4 provinceNo
                        //cellIterator.next(); //5 municipalityno
                        //cellIterator.next(); //6 municipality
                        //cellIterator.next(); //8 brgyNo 99
                        //cellIterator.next(); //11 household# TODO: to be generated by system
                        //cellIterator.next(); //12 institutionallivingquarter 99#
                        //cellIterator.next(); //19 Timestart (unnecessary field)
                        //cellIterator.next(); //20 Timeend (unnecessary field)
                        //cellIterator.next(); //21 Result?? (unnecessary field)
                        //cellIterator.next(); //22 Next visit 99# (unnecessary field)

                        hhb.totalNumber(getIntCellValue(row, 15)); //16 totalnoofhousehold Should it be computed?#
                        hhb.houseOwnership(Ownership.getByCode(getIntCellValue(row, 87))); //89
                        hhb.lotOwnership(Ownership.getByCode(getIntCellValue(row, 88))); //90
                        hhb.lighting(Lighting.getByCode(getIntCellFirstValue(row, 89)));
                        hhb.cookingFuel(CookingFuel.getByCode(getIntCellFirstValue(row, 90)));
                        hhb.waterSource(WaterSource.getByCode(getIntCellFirstValue(row, 91)));
                        hhb.garbageDisposal(GarbageDisposal.getByCode(getIntCellFirstValue(row, 92)));
                        hhb.hasTrashSegregation(YesOrNo.getByCode(getIntCellFirstValue(row, 93))); //95
                        hhb.toiletFacility(ToiletFacility.getByCode(getIntCellFirstValue(row, 94)));
                        hhb.buildingType(BuildingType.getByCode(getIntCellFirstValue(row, 95)));
                        hhb.buildingMaterial(BuildingMaterial.getByCode(getIntCellFirstValue(row, 96)));

                        // Survey Info
                        sb.respondent(getStringCellValue(row, 13)); //14
                        //sb.visit(getIntCellValueRemoveString(row, 16)); //17 visit (should be computed)
                        sb.interviewDate(getDateCellValue(row, 17)); //18
                        //sb.interviewer(getStringCellValue(row, 22)); //23
                        //sb.interviewerSupervisor(getStringCellValue(row, 23)); //24
                        //sb.encodeDate(getDateCellValue(row, 24)); //25
                        //sb.encoder(getStringCellValue(row, 25)); //26
                        //sb.encoderSupervisor(getStringCellValue(row, 26)); //27
                    }

                    // Resident info
                    rb.lastName(getStringCellValue(row, 27));
                    rb.firstName(getStringCellValue(row, 28));
                    rb.middleName(getStringCellValue(row, 29)); //30
                    rb.relationshipToHead(relation);
                    rb.sex(Sex.getByCode(getIntCellValue(row, 31)));
                    rb.age(getIntCellValue(row, 32));
                    rb.yearOfBirth(getIntCellValue(row, 33)); //34
                    rb.monthOfBirth(getMonthCellValue(row, 34));
                    rb.placeOfBirthBrgy(getStringCellValue(row, 35));
                    rb.placeOfBirthMunicipality(getStringCellValue(row, 36));
                    rb.nationality(Nationality.getByCode(getIntCellValue(row, 37)));
                    rb.civilStatus(CivilStatus.getByCode(getIntCellValue(row, 38))); //40
                    rb.religion(getStringCellValue(row, 39));
                    rb.ethnicity(getStringCellValue(row, 40));
                    rb.educationalAttainment(Education.getByCode(getIntCellValue(row, 41)));
                    rb.enrollmentStatus(Enrollment.getByCode(getIntCellValue(row, 42)));
                    rb.schoolLevel(SchoolLevel.getByCode(getIntCellValue(row, 43))); //45
                    rb.placeOfSchool(getStringCellValue(row, 44));

                    rb.parentalStatus(ParentalStatus.getByCode(getIntCellValue(row, 62)));
                    rb.registeredSeniorCitizen(YesOrNo.getByCode(getIntCellValue(row, 63))); //65
                    rb.votingArea(Barangay.getByDescription(getStringCellValue(row, 64)));

                    // Economic Activity
                    rb.monthlyIncome(getStringCellValue(row, 45));
                    rb.sourceOfIncome(IncomeSource.getByCode(getIntCellValue(row, 46)));
                    rb.workStatus(WorkStatus.getByCode(getIntCellValue(row, 47)));
                    rb.placeOfWork(getStringCellValue(row, 48)); //50
                    rb.CTCIssued(YesOrNo.getByCode(getIntCellValue(row, 83))); //85
                    rb.CTCIssuedBarangay(getStringCellValue(row, 84));
                    //row, ; // "Q43-skill development training
                    Cell skills = row.getCell(85, RETURN_BLANK_AS_NULL);
                    if (isUndefined(skills)) {
                        // No skills
                    } else if (CellType.NUMERIC.equals(skills.getCellTypeEnum())) {
                        if (skills.getNumericCellValue() != 99.0D) {
                            List.of(Skill.getByCode(getIntCellValue(row, 85)));
                        }
                    } else if (CellType.STRING.equals(skills.getCellTypeEnum())) {
                        String value = getStringCellValue(row, 85);
                        rb.skills(Arrays.stream(value.split("&|,|\\.|\\*"))
                                .map(r -> Skill.getByCode(parseInt(r)))
                                .collect(Collectors.toList()));
                    }

                    // Health Record
                    rb.placeOfDelivery(DeliveryPlace.getByCode(getIntCellValue(row, 49)));
                    rb.birthAttendant(getStringCellValue(row, 50));
                    rb.immunization(getStringCellValue(row, 51));
                    rb.livingChildren(getIntCellValue(row, 52));
                    rb.livingChildrenSub(getIntCellValue(row, 53)); //55
                    rb.FPMethod(FPMethod.getByCode(getIntCellFirstValue(row, 54)));
                    rb.sourceOfFP(SourceOfFP.getByCode(getIntCellFirstValue(row, 55)));
                    rb.intentToUseFP(YesOrNo.getByCode(getIntCellFirstValue(row, 56)));
                    rb.intentToUseFPSub(FPMethod.getByCode(getIntCellFirstValue(row, 57)));
                    rb.healthInsurance(HealthInsurance.getByCode(getIntCellFirstValue(row, 58))); //60
                    rb.facility(Facility.getByCode(getIntCellFirstValue(row, 59)));
                    rb.reasonOfVisit(ReasonOfVisit.getByCode(getIntCellFirstValue(row, 60))); // If non-numeric catch exception and set 99
                    rb.disability(getStringCellValue(row, 61));

                    // Residency Info
                    rb.previousBarangayFiveYr(getStringCellValue(row, 65));
                    rb.previousMunicipalityFiveYr(getStringCellValue(row, 66));
                    rb.previousBarangaySixMo(getStringCellValue(row, 67));
                    rb.previousMunicipalitySixMo(getStringCellValue(row, 68)); //70
                    rb.yearsOfStay(getIntCellValueRemoveString(row, 69));
                    rb.monthsOfStay(getIntCellValueRemoveString(row, 70));
                    rb.residentType(ResidentType.getByCode(getIntCellValue(row, 71)));
                    rb.monthOfTransfer(getMonthCellValue(row, 72));
                    rb.yearOfTransfer(getIntCellValue(row, 73)); //75
                    rb.reasonForLeavingA(ReasonForLeaving.getByCode(getIntCellValue(row, 74)));
                    rb.reasonForLeavingB(ReasonForLeaving.getByCode(getIntCellValue(row, 75)));
                    rb.reasonForLeavingC(ReasonForLeaving.getByCode(getIntCellValue(row, 76)));
                    //row, ; // Q39-returntopreviousresident
                    //row, ; // Q39-returntopreviousresident-Response  //80
                    rb.reasonForTransferA(ReasonForTransfer.getByCode(getIntCellValue(row, 79)));
                    rb.reasonForTransferB(ReasonForTransfer.getByCode(getIntCellValue(row, 80)));
                    rb.reasonForTransferC(ReasonForTransfer.getByCode(getIntCellValue(row, 81)));
                    rb.durationOfStay(getIntCellValue(row, 82));

                    // Extra info
                    //cellIterator.next(); //Q54-age //99
                    //cellIterator.next(); //Q54A-causeofdeath //100
                    //cellIterator.next(); //Q55-age
                    //cellIterator.next(); //Q55-sex
                    //cellIterator.next(); //Q55-causeofdeath
                    //cellIterator.next(); //Q56A cause of death
                    //cellIterator.next(); //Q56B cause of death
                    //cellIterator.next(); //Q56C cause of death
                    //cellIterator.next(); //Q57A brgy needs
                    //cellIterator.next(); //Q57B brgy needs
                    //cellIterator.next(); //Q57C brgy needs
                    //cellIterator.next(); //Q58 brgy
                    //cellIterator.next(); //Q58 municipality
                    //cellIterator.next(); //Q58 province

                    Record.RecordBuilder builder = Record.builder();
                    builder.row(row.getRowNum()+1);
                    builder.survey(sb.build());
                    builder.household(hhb.build());
                    builder.resident(rb.build());
                    records.add(builder.build());
                } catch(Exception e) {
                    Logger.error("Failed to parse row %s [Error: %s]", row.getRowNum()+1, e.getMessage());
                    hasError = true;
                }
            }
        } catch(Exception e) {
            Logger.fatal(e, "Import failed with file name %s", file.getName());
            throw e;
        }

        if (hasError) {
            Logger.error("There has been errors on parsing the document, please make sure the fields are properly formatted");
            return Lists.newArrayList();
        }
        return records;
    }

    private static Integer getIntCellValue(Row row, int rowNum) {
        Cell cell = row.getCell(rowNum, RETURN_BLANK_AS_NULL);
        if (isUndefined(cell)) return null;
        if (CellType.NUMERIC.equals(cell.getCellTypeEnum())) {
            return Double.valueOf(cell.getNumericCellValue()).intValue();
        } else if (CellType.STRING.equals(cell.getCellTypeEnum())) {
            return parseInt(cell.getStringCellValue());
        }
        return null;
    }

    private static String getStringCellValue(Row row, int rowNum) {
        Cell cell = row.getCell(rowNum, RETURN_BLANK_AS_NULL);
        if (isUndefined(cell)) return null;
        if (CellType.STRING.equals(cell.getCellTypeEnum())) {
            return cell.getStringCellValue().trim().toUpperCase();
        } else if (CellType.NUMERIC.equals(cell.getCellTypeEnum())) {
            return "" + Double.valueOf(cell.getNumericCellValue()).intValue();
        }
        return null;
    }

    private static Integer getIntCellValueRemoveString(Row row, int rowNum) {
        Cell cell = row.getCell(rowNum, RETURN_BLANK_AS_NULL);
        if (isUndefined(cell)) return null;
        if (CellType.NUMERIC.equals(cell.getCellTypeEnum())) {
            return Double.valueOf(cell.getNumericCellValue()).intValue();
        } else if (CellType.STRING.equals(cell.getCellTypeEnum())) {
            return parseInt(cell.getStringCellValue().replaceAll("\\D+",""));
        }
        return null;
    }

    private static Integer getIntCellFirstValue(Row row, int rowNum) {
        Cell cell = row.getCell(rowNum, RETURN_BLANK_AS_NULL);
        if (isUndefined(cell)) return null;
        if (CellType.NUMERIC.equals(cell.getCellTypeEnum())) {
            return getIntCellValue(row, rowNum);
        } else if (CellType.STRING.equals(cell.getCellTypeEnum())) {
            String value = getStringCellValue(row, rowNum);
            if (isUndefined(value)) return null;
            return Arrays.stream(value.split("&|,|\\.|\\*"))
                    .findFirst()
                    .map(r -> parseInt(r))
                    .get();
        }
        return null;
    }

    private static Month getMonthCellValue(Row row, int rowNum) {
        Cell cell = row.getCell(rowNum, RETURN_BLANK_AS_NULL);
        if (isUndefined(cell)) return null;
        if (CellType.STRING.equals(cell.getCellTypeEnum())) {
            String value = cell.getStringCellValue();
            try {
                return Month.of(Integer.parseInt(value));
            } catch (NumberFormatException nfe) {
                return Month.valueOf(value.toUpperCase());
            }
        } else if (CellType.NUMERIC.equals(cell.getCellTypeEnum())) {
            int month = getIntCellValue(row, rowNum);
            if (month < 1 || month > 12) return null;
            return Month.of(month);
        }
        return null;
    }

    private static Date getDateCellValue(Row row, int rowNum) {
        Cell cell = row.getCell(rowNum, RETURN_BLANK_AS_NULL);
        if (isUndefined(cell)) return null;
        if (CellType.NUMERIC.equals(cell.getCellTypeEnum())) {
            return cell.getDateCellValue();
        }
        return null;
    }

    private static boolean isUndefined(String value) {
        return (value == null || value.isBlank() || "99".equals(value) || "98".equals(value)) ? true : false;
    }

    private static boolean isUndefined(Double value) {
        return (value == null || value == 99.0D || value == 98.0D) ? true : false;
    }

    private static boolean isUndefined(Cell cell) {
        if (cell == null) {
            return true;
        } else if (CellType.STRING.equals(cell.getCellTypeEnum())) {
            return isUndefined(cell.getStringCellValue());
        } else if (CellType.NUMERIC.equals(cell.getCellTypeEnum())) {
            return isUndefined(cell.getNumericCellValue());
        } else {
            return false;
        }
    }

    private static Integer parseInt(String value) {
        try {
            return Integer.parseInt(value.trim());
        } catch (NumberFormatException nfe) {
            Logger.warn("Failed to parse column with value %s. Value will be set as Others.", value);
            return -1;
        }
    }
}
